### ISSUE TITLE
Clarify with backend

### ISSUE THREAD

**Issue by LisaKSH** [digitalfabrik/coldaid-frontend#3]
- How do they gonna provide Real Time Data/Update
--> Schnittstelle wird noch definiert 
- How are they gonna represent the Data? Create Dummy Data in JSON, do they have a template? -> Wir machen Excel Liste

**Comment by CarmenLea** [comment]
- Backend arbeitet Neuerung in Dummydata Json ein 
- Übersetzung der Strings machen Backend und Frontend getrennt (Parameter in den Routen) 
- Frontend erhält Endpoint Liste von Backend

**Comment by timobrembeck** [comment]
List of endpoints:
- `/regions`
 Get a list of all active regions. Contains following fields:
`name`, `slug`, `aliases`, `administrative_division`, `latitude`, `longitude`, `postal_code`
- `/<region>/languages`
 Get a list of all active languages of one region. Contains following fields:
`native_name`, `english_name`, `text_direction`
- `/<region>/<language>/accomodations`
 Get a list of all accomodations in a specific region (see dummy data for format)
