### ISSUE TITLE
Show live location on map

### ISSUE THREAD

**Issue by LisaKSH** [digitalfabrik/coldaid-frontend#9]
User can see his/her current location on a map

**Comment by radoslavvlaskovski** [comment]
Map data source: https://www.openstreetmap.org (supervisor comment: already used in the bigger project)
Copyright: https://www.openstreetmap.org/copyright (**OSM needs to be contributed**)

Possible ways to integrate it: 

| Name   | Contributors  | Commits | Comment | Link | Used By |
|---|---|---|---|---|---|
| Pigeon Maps | 13 | 400 |  ReactJS framework with support for OSM & other maps | https://github.com/mariusandra/pigeon-maps | 300 |
| OSM UI React | 2 | 570 | Not official from React/OSM | https://gitlab.com/osm-ui/react | ? |
| React Leaflet | 87 | 450 | Leaflet is open-source JavaScript library for mobile-friendly interactive maps | https://react-leaflet.js.org/en/ | 7k+ |
| OSMJS | 1 | 10 | not official | https://github.com/csr/OpenStreetMap-ReactJS | ? |

Most supported and most used according to the able above is **React Leaflet**.
